
version: '3'

services:
  product-api:
    build: .
    container_name: product-api
    restart: always
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - product-mongodb
    networks:
      - product-network
  product-mongodb:
    image: bitnami/mongodb:latest
    restart: always
    container_name: product-mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    volumes:
      - product-mongodb-data:/data
    networks:
      - product-network

volumes:
  product-mongodb-data:

networks:
  product-network:
    driver: bridge